ALTER TABLE HANDLING_UNIT ADD CONSTRAINT FK_HANDLING_UNIT_BASE_HU FOREIGN KEY (BASE_HU) REFERENCES HANDLING_UNIT (ID);
ALTER TABLE HANDLING_UNIT ADD CONSTRAINT FK_HANDLING_UNIT_LOCATION_ID FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION (LOCATION_ID);
ALTER TABLE LOCATION_STATUS ADD CONSTRAINT FK_LOCATION_STATUS_LOCATION_ID FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION (LOCATION_ID);
ALTER TABLE DIMENSION ADD CONSTRAINT FK_DIMENSION_LOCATION_ID FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION (LOCATION_ID);
ALTER TABLE HU_CONTAINS ADD CONSTRAINT FK_HU_CONTAINS_ID FOREIGN KEY (ID) REFERENCES HANDLING_UNIT (ID);
ALTER TABLE HU_CONTAINS ADD CONSTRAINT FK_HU_CONTAINS_CONTAINS FOREIGN KEY (CONTAINS) REFERENCES HANDLING_UNIT (ID);
