ALTER TABLE HANDLING_UNIT DROP CONSTRAINT FK_HANDLING_UNIT_BASE;
ALTER TABLE HANDLING_UNIT DROP CONSTRAINT FK_HANDLING_UNIT_LOCATION_ID;
ALTER TABLE LOCATION_STATUS DROP CONSTRAINT FK_LOCATION_STATUS_LOCATION_ID;
ALTER TABLE DIMENSION DROP CONSTRAINT FK_DIMENSION_LOCATION_ID;
ALTER TABLE HU_CONTAINS DROP CONSTRAINT FK_HU_CONTAINS_ID;
ALTER TABLE HU_CONTAINS DROP CONSTRAINT FK_HU_CONTAINS_CONTAINS;
