DROP TABLE APPL_CONFIG IF EXISTS;
DROP TABLE LOCATION_STATUS IF EXISTS;
DROP TABLE DIMENSION IF EXISTS;
DROP TABLE CONTAINS_HU IF EXISTS;
DROP TABLE HANDLING_UNIT IF EXISTS;
DROP TABLE LOCATION IF EXISTS;
